### ISSUE TITLE
Workspaces icon is not shown correcltly.

### ISSUE THREAD

**Issue by vbabiy** [tobealive/trilum-eote-theme#1]
![image](https://user-images.githubusercontent.com/15382/210095321-e29c6b43-9997-4b29-9e0f-1df7609a9a1d.png)

**Comment by ttytm** [comment]
Hey @vbabiy, thanks for reporting the issue. I'll investigate now!

**Comment by ttytm** [comment]
Should be fixed. Please let me know if the issue persists for you. Have a good new year!

**Comment by vbabiy** [comment]
@tobealive looks great thanks.

**Comment by vbabiy** [comment]
@tobealive just noticed this is also broken on hoisted notes:

![image](https://user-images.githubusercontent.com/15382/212886216-6d39c4e8-0384-4c7f-a9f7-f33e70b02178.png)

**Comment by ttytm** [comment]
Hey @vbabiy 
It should be fixed now. 

Please let me know if it works for you and don't hesitate to reach out if you experience further issues.

**Comment by vbabiy** [comment]
@tobealive amazing. Thank you
