### ISSUE TITLE
Checkbox are not correct

### ISSUE THREAD

**Issue by vbabiy** [tobealive/trilum-eote-theme#9]
![image](https://user-images.githubusercontent.com/15382/212908821-aaafc233-de40-4ff2-882b-4e914a07d63d.png)

**Comment by ttytm** [comment]
Thanks for reporting the issues @vbabiy  👍

It's likely a regression of: daa117b1765889a8512a93f0855115905604ae96

I'll check on it soon!

**Comment by vbabiy** [comment]
Looks good
